[package]
name = "cyber-std"
version = "0.2.1"
authors = ["CyberHead"]
edition = "2018"
description = "Bindings for CustomMsg and CustomQuery for the Cyber"
repository = "https://github.com/cybercongress/cw-cyber"
homepage = "https://github.com/cybercongress/go-cyber"
license = "Apache-2.0"
readme = "README.md"


[dependencies]
cosmwasm-std = { version = "1.0.0", features = ["iterator"] }
schemars = "0.8.1"
cw721 = { version = "0.13.2" }
cid = { version = "0.8.0" }
serde = { version = "1.0.127", default-features = false, features = ["derive"] }
thiserror = { version = "1.0.21" }

[dev-dependencies]
cosmwasm-schema = { version = "1.0.0" }


